"""Add conversation_memory table

Revision ID: 435d167b71ef
Revises: 
Create Date: 2025-11-03 15:55:46.697189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435d167b71ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memory',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('message_role', sa.String(length=50), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_conversation_memory_conversation_id'), 'conversation_memory', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_memory_message_timestamp'), 'conversation_memory', ['message_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_memory_message_timestamp'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_conversation_id'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    # ### end Alembic commands ###
