"""add-debugging-column-in-conversation-table

Revision ID: ae05596226b9
Revises: f3b7fa1666d0
Create Date: 2025-11-24 13:22:08.737677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae05596226b9"
down_revision: Union[str, Sequence[str], None] = "f3b7fa1666d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_memory",
        sa.Column(
            "chat_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "conversation_memory",
        sa.Column(
            "contextual_messages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "conversation_memory",
        sa.Column("document_ids", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "conversation_memory",
        sa.Column("thoughts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation_memory", "thoughts")
    op.drop_column("conversation_memory", "document_ids")
    op.drop_column("conversation_memory", "contextual_messages")
    op.drop_column("conversation_memory", "chat_params")
    # ### end Alembic commands ###
