"""empty message

Revision ID: f3b7fa1666d0
Revises: 435d167b71ef
Create Date: 2025-11-05 16:24:05.008469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3b7fa1666d0"
down_revision: Union[str, Sequence[str], None] = "435d167b71ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old default (integer sequence)
    op.alter_column(
        "conversation_memory",
        "message_id",
        existing_type=sa.INTEGER(),
        server_default=None,
    )

    # Change type to UUID with appropriate casting
    op.alter_column(
        "conversation_memory",
        "message_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="message_id::text::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Change type back to INTEGER
    op.alter_column(
        "conversation_memory",
        "message_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="1",
    )  # Generate sequential integers starting from 1

    # ### end Alembic commands ###
